c=int(input("Enter the value of c:"))
print((9/5)*c+32)
f=int(input("Enter the value of f:"))
print((f-32)*5/9)
l=int(input("Enter the value of l:"))
w=int(input("Enter the value of w:"))
print(l*w)
r=int(input("Enter the value of r:"))
print(((4/3)*3.142)*r**3)
name='M RASHID BHATTI'
print("The given name is :",name)
print("The name is title case is:",name.title())
print("The name is lower case is:",name.lower())
print("The name is upper case is:",name.upper())
