r=int(input("Enter the value of r:"))
print(r*0.4)
r=int(input("Enter the value of r:"))
print(r+40)
p=int(input("Enter the value of p:"))
r=int(input("Enter the value of r:"))
t=int(input("Enter the value of t:"))
print(p*r*t/100)
name=input("Enter the name:")
sub1=int(input("Enter the sub1"))
sub2=int(input("Enter the sub2:"))
sub3=int(input("Enter the sub3:"))
sub4=int(input("Enter the sub4:"))
total = sub1+sub2+sub3+sub4
print("total no : ",total)
print((total/400)*100)
print(total/4)